apimServiceName: destination-apim-001
# namedValues:
#   - name: environment
#     properties:
#       displayName: environment
#       value: "https://www.search2.com"
#   - name: mysecretvalue
#     properties:
#       displayName: mysecretvalue
#       keyVault:
#         identityClientId: [identity client id goes here]
#         secretIdentifier: [your url here]
#   - name: testSecret
#     properties:
#       displayName: testSecret
#       value: "{#testSecretValue#}"
#   - name: helloworldfromfuncapp-key
#     properties:
#       displayName: helloworldfromfuncapp-key
#       value: "{#helloworldfromfuncappkey#}"
#   - name: 634e022983908257b35630b0
#     properties:
#       displayName: helloworldfromlogicapp_manual-invoke_634e022983908257b35630b0
#       value: "{#helloworldfromlogicapp#}"  
loggers:
    # - name: appi-mfg-pg-xabg
    #   properties:
    #     loggerType: applicationInsights
    #     description: prod application insights
    #     resourceId: "/subscriptions/38bfc61d-d89a-4df6-b8fb-0c14568dcf29/resourceGroups/dns-hub-rg/providers/Microsoft.Insights/components/appi-mfg-pg-xabg"
    #     credentials:
    #       instrumentationKey: "655ba34f4634611ba8312d26"
    #     isBuffered: true
diagnostics:
  #  - name: applicationinsights
  #    properties:
  #      verbosity: Error
  #      loggerId: "/subscriptions/38bfc61d-d89a-4df6-b8fb-0c14568dcf29/resourceGroups/dns-hub-rg/providers/Microsoft.ApiManagement/service/destination-apim-001/loggers/appi-mfg-pg-xabg"
backends:
#   - name: helloworldfromfuncapp
#     properties:
#       url: "https://helloworldfromprodfuncapp.azurewebsites.net/api"
#       resourceid: "https://management.azure.com/subscriptions/[subscription Guid goes here]/resourceGroups/rg-apim-lab-prod/providers/Microsoft.Web/sites/helloworldfromprodfuncapp"
#   - name: LogicApp_helloworldfromlogicapp_rg-apim-lab_77fadbdc74f14ce88962b34400a1f170
#     properties:
#       url: "https://prod-75.eastus.logic.azure.com/workflows/[guid goes here]/triggers"
#       resourceid: "https://management.azure.com/subscriptions/[subscription Guid goes here]/resourceGroups/rg-apim-lab-prod/providers/Microsoft.Logic/workflows/helloworldfromprodlogicapp"
apis:
  # - name: eShopOnDapr-Basket-Api
  #   diagnostics:
  #     - name: appi-mfg-pg-xabg
  #       properties:
  #         verbosity: Error
  #         loggerId: "/subscriptions/38bfc61d-d89a-4df6-b8fb-0c14568dcf29/resourceGroups/dns-hub-rg/providers/Microsoft.ApiManagement/service/destination-apim-001/loggers/appi-mfg-pg-xabg"
